# This is a basic workflow to help you get started with Actions

name: deploy-sa

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sign in to Azure
        uses: azure/login@v1
        with:
          client-id: 
          tenant-id: 
          subscription-id: 

      - name: deploy RG
        uses: azure/cli@v1
        with:
         inlineScript:
          
          
      - name: deploy storage
        uses: azure/arm-deploy@v1
        with:
         deploymentName: ${{github.run_Number}}
         resourceGroupName: 
         template:
