# This is a basic workflow to help you get started with Actions

name: deploy-sa

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
 RG_NAME: RG4
 RG_LOC: WestEurope

permissions:
 id-token: write
 contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZ_CLIENT_ID}}
          tenant-id: ${{secrets.AZ_TENANT_ID}}
          subscription-id: ${{secrets.AZ_SUB_ID}}

      - name: deploy RG
        uses: azure/cli@v1
        with:
         inlineScript:
          az group create -n ${{env.RG_NAME}} -l ${{env.RG_LOC}}
          
          
      - name: deploy storage
        uses: azure/arm-deploy@v1
        with:
         deploymentName: ${{github.run_Number}}
         resourceGroupName: ${{env.RG_NAME}}
         template: ./sa.bicep
